# Generated by Django 3.2.3 on 2021-05-28 04:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
